version: "3.9"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=skistationDB
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: devops-spring_app   # Assuming this is the image you built for your Spring Boot app
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    command: ["java", "-jar", "app.jar"]


